spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_application?createDatabaseIfNotExist=true
    username: root
    password: Athimac12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  output:
    ansi:
     enabled: always
logging:
   level:
     com:
       security:
         bank: DEBUG
   file:
     name: application.log

management:
   endpoints:
     web:
       exposure:
         include: '*'
   endpoint:
     health:
       show-details: ALWAYS
server:
  port:8080